### PR TITLE
New Robot Icons

### PR DESCRIPTION
**Pull request by wylie**
Adding some new Futurama robot icons.
- adding an array of all the icons
- changing the URL of the new icons
- adding a random icon each time

### CODE REVIEW

**Comment by Dragonegger2** [comment]
Looks like it does what it was intended to do so far as I can tell.

**Comment by wylie** [comment]
Yeah, not sure if it will do the right thing until it gets into @Rogibb111 repo

**Comment by wylie** [comment]
@Rogibb111 merge this in and make a new build we can check out!

**Comment by Rogibb111** [comment]
@wylie ill make any changes necessary if it needs it

**Pull request merged**
